/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.iberotec;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.edu.iberotec.models.*;

/**
 *
 * @author Jhonatan
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    ArrayList<Cliente> listado;
    int contID = 0;
    Cliente ultimo;
    Cliente clienteActualTablaPersonas;
    ArrayList<Persona> listaPeronasClienteActual;
    public Index() {        
        initComponents();
        actualizarIDCliente();
        lblErrorTelefono.setText("");
        lblMensajeTelefonoPersona.setText("");
        btnInsertarPersona.setEnabled(false);
        btnEliminarPersona.setEnabled(false);
        try{
            rellenarTablaCliente();
            llenarCbCliente(cbClientesPersonas);
        }catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        lblErrorTelefono = new javax.swing.JLabel();
        txtApellidoCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        btnInsertarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCliente = new javax.swing.JTable();
        btnEliminarCliente = new javax.swing.JButton();
        btnBorrarCamposClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbClientesPersonas = new javax.swing.JComboBox();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtApellidoPersona = new javax.swing.JTextField();
        txtDireccionPersona = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTelefonoPersona = new javax.swing.JTextField();
        lblMensajePersona = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPersona = new javax.swing.JTable();
        btnInsertarPersona = new javax.swing.JButton();
        lblMensajeTelefonoPersona = new javax.swing.JLabel();
        btnEliminarPersona = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("TELÉFONO:");

        lblErrorTelefono.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblErrorTelefono.setForeground(new java.awt.Color(153, 0, 0));
        lblErrorTelefono.setText("Aquí saldran los errores de formato de número");

        btnInsertarCliente.setText("INSERTAR CLIENTE");
        btnInsertarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarClienteActionPerformed(evt);
            }
        });

        TablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Direccion", "Telefono", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaCliente);

        btnEliminarCliente.setText("ELIMINAR CLIENTE");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        btnBorrarCamposClientes.setText("BORRAR LOS CAMPOS");
        btnBorrarCamposClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCamposClientesActionPerformed(evt);
            }
        });

        jLabel1.setText("NOMBRE:");

        jLabel6.setText("ID:");

        jLabel2.setText("APELLIDO:");

        txtIDCliente.setEditable(false);

        jLabel3.setText("DIRECCION:");

        btnBuscarCliente.setText("Buscar ID");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminarCliente)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtApellidoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtDireccionCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnBorrarCamposClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(lblErrorTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))))
                                .addContainerGap())
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnInsertarCliente)
                .addGap(54, 600, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorTelefono))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarCliente)
                    .addComponent(btnBorrarCamposClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCliente))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Seleccionar un cliente para el registro:");

        cbClientesPersonas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cbClientesPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientesPersonasActionPerformed(evt);
            }
        });

        txtDireccion.setEditable(false);

        txtTelefono.setEditable(false);

        jLabel7.setText("Nombre:");

        jLabel8.setText("Apellidos:");

        jLabel9.setText("Dirección:");

        jLabel10.setText("ID:");

        jLabel11.setText("Teléfono:");

        txtID.setEditable(false);

        txtNombre.setEditable(false);

        txtApellido.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel12.setText("Datos del cliente: ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setText("Datos de la persona: ");

        txtNombrePersona.setEditable(false);

        jLabel15.setText("Nombre:");

        jLabel16.setText("Apellidos:");

        txtApellidoPersona.setEditable(false);

        txtDireccionPersona.setEditable(false);

        jLabel17.setText("Dirección:");

        jLabel18.setText("Teléfono:");

        txtTelefonoPersona.setEditable(false);

        lblMensajePersona.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblMensajePersona.setForeground(new java.awt.Color(204, 0, 0));
        lblMensajePersona.setText("Seleccione un cliente para el registro");

        TablaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Direccion", "Telefono", "ID Cliente", "Nombre Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaPersona);
        if (TablaPersona.getColumnModel().getColumnCount() > 0) {
            TablaPersona.getColumnModel().getColumn(2).setPreferredWidth(200);
            TablaPersona.getColumnModel().getColumn(4).setPreferredWidth(35);
        }

        btnInsertarPersona.setText("Insertar Persona");
        btnInsertarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPersonaActionPerformed(evt);
            }
        });

        lblMensajeTelefonoPersona.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lblMensajeTelefonoPersona.setForeground(new java.awt.Color(204, 0, 0));
        lblMensajeTelefonoPersona.setText("Formato inválido");

        btnEliminarPersona.setText("Eliminar Persona");
        btnEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cbClientesPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 277, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtApellido)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16))
                                    .addComponent(jLabel18))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDireccionPersona)
                                        .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMensajeTelefonoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(lblMensajePersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminarPersona)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(btnInsertarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbClientesPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMensajePersona)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtApellidoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtDireccionPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMensajeTelefonoPersona))))
                .addGap(3, 3, 3)
                .addComponent(btnInsertarPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarPersona)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Personas", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Animales", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab6", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarClienteActionPerformed
        listado =  PersistenciaCliente.LoadData();
        lblErrorTelefono.setText("");
        Cliente cli = new Cliente();
        cli.setNombre(txtNombreCliente.getText());
        cli.setApellido(txtApellidoCliente.getText());
        cli.setDireccion(txtDireccionCliente.getText());

        try{
            cli.setTelefono(Integer.parseInt(txtTelefonoCliente.getText()));
            cli.setId(Integer.parseInt(txtIDCliente.getText()));
            contID++;
            listado.add(cli);
            PersistenciaCliente.SaveData(listado);
            rellenarTablaCliente();
            txtNombreCliente.setText("");
            txtApellidoCliente.setText("");
            txtDireccionCliente.setText("");
            txtTelefonoCliente.setText("");
            txtIDCliente.setText("" + contID);
            //Luego se pondrá un método actualizar todos los combobox de los clientes xd :)
            actualizarCbCliente(cbClientesPersonas);

        }catch(NumberFormatException e){
            lblErrorTelefono.setText("Formato de número inválido");
        }

    }//GEN-LAST:event_btnInsertarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        listado =  PersistenciaCliente.LoadData();
        int[] eliminarDatos = TablaCliente.getSelectedRows();
        int indice = eliminarDatos.length - 1;
        if (indice >= 0) {
            for(int x = indice; indice >= 0; indice--){
                int elim = eliminarDatos[indice];
                System.out.println("" + elim);
                listado.remove(elim);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona uno o mas datos de la tabla" , "Mensaje", JOptionPane.WARNING_MESSAGE);
        }
        PersistenciaCliente.SaveData(listado);
        rellenarTablaCliente();
        actualizarIDCliente();
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnBorrarCamposClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCamposClientesActionPerformed
        txtIDCliente.setText("");
        txtNombreCliente.setText("");
        txtApellidoCliente.setText("");
        txtDireccionCliente.setText("");
        txtTelefonoCliente.setText("");
    }//GEN-LAST:event_btnBorrarCamposClientesActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
        listado = PersistenciaCliente.LoadData();
        String b = txtBuscar.getText();
        try{
            int b2 = Integer.parseInt(b);
            String x = "";
            if(b2 <= listado.size() && b2 > 0){
                for(Cliente cli : listado){
                    int n = cli.getId();
                    if(n == b2){
                        x = x +"Id : "+ cli.getId()+ "\n"+ "Nombre :"
                        + " " + cli.getNombre() +"\n" + "Apellido: "
                        + cli.getApellido()+"\n" + "Direccion: "
                        + cli.getDireccion() +"\n" + "Telefono : "
                        + cli.getTelefono();

                    }

                }
                JOptionPane.showMessageDialog(this,x);}
            else {JOptionPane.showMessageDialog(this, "No existe este ID");}

        }catch(NumberFormatException e){

            JOptionPane.showMessageDialog(this, "solo numeros enteros");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void cbClientesPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientesPersonasActionPerformed

        listado =  PersistenciaCliente.LoadData();
        lblMensajePersona.setText("");
        lblMensajeTelefonoPersona.setText("");
        if(!"Seleccione".equals((String) cbClientesPersonas.getSelectedItem())){
            int indiceClienteActual = cbClientesPersonas.getSelectedIndex() - 1;
            //System.out.println("" + num);
            try{
                clienteActualTablaPersonas = listado.get(indiceClienteActual);
                actualizarTablaPersona(clienteActualTablaPersonas);
                txtID.setText("" + clienteActualTablaPersonas.getId());
                txtNombre.setText(clienteActualTablaPersonas.getNombre());
                txtApellido.setText(clienteActualTablaPersonas.getApellido());
                txtDireccion.setText(clienteActualTablaPersonas.getDireccion());
                txtTelefono.setText("" + clienteActualTablaPersonas.getTelefono());
                lblMensajePersona.setText("Complete los campos requeridos");
                listaPeronasClienteActual = clienteActualTablaPersonas.getListaPersonas();
                txtNombrePersona.setEditable(true);
                txtApellidoPersona.setEditable(true);
                txtTelefonoPersona.setEditable(true);
                txtDireccionPersona.setEditable(true);
                btnInsertarPersona.setEnabled(true);
                btnEliminarPersona.setEnabled(true);
            }catch(java.lang.ArrayIndexOutOfBoundsException ny){
                //error producido constantemente al insertar clientes pero ignorado ya que no causa daño.
            }
        }else{
            lblMensajePersona.setText("Seleccione un cliente para el registro");
            txtID.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtNombrePersona.setEditable(false);
            txtApellidoPersona.setEditable(false);
            txtTelefonoPersona.setEditable(false);
            txtDireccionPersona.setEditable(false);
            btnInsertarPersona.setEnabled(false);
            btnEliminarPersona.setEnabled(false);
            LimpiarTablaPersona();
        }

    }//GEN-LAST:event_cbClientesPersonasActionPerformed

    private void btnInsertarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPersonaActionPerformed
        int indiceClienteActual = cbClientesPersonas.getSelectedIndex() - 1;
        lblMensajeTelefonoPersona.setText("");
        listaPeronasClienteActual = clienteActualTablaPersonas.getListaPersonas();
        Persona p = new Persona();
        try{    
            p.setTelefono(Integer.parseInt(txtTelefonoPersona.getText()));
            p.setNombre(txtNombrePersona.getText());
            p.setApellidos(txtApellidoPersona.getText());
            p.setDireccion(txtDireccionPersona.getText());
            listaPeronasClienteActual.add(p);
            clienteActualTablaPersonas.setListaPersonas(listaPeronasClienteActual);
            listado.set(indiceClienteActual, clienteActualTablaPersonas);
            actualizarTablaPersona(clienteActualTablaPersonas);
            PersistenciaCliente.SaveData(listado);
            txtNombrePersona.setText("");
            txtApellidoPersona.setText("");
            txtTelefonoPersona.setText("");
            txtDireccionPersona.setText("");
        }catch(NumberFormatException EV){lblMensajeTelefonoPersona.setText("Formato Inválido");}
    }//GEN-LAST:event_btnInsertarPersonaActionPerformed

    private void btnEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonaActionPerformed
        int indiceClienteActual = cbClientesPersonas.getSelectedIndex() - 1;
        lblMensajeTelefonoPersona.setText("");
        listaPeronasClienteActual = clienteActualTablaPersonas.getListaPersonas();
        int[] eliminarDatos = TablaPersona.getSelectedRows();
        int indice = eliminarDatos.length - 1;
        if (indice >= 0) {
            for(int x = indice; indice >= 0; indice--){
                int elim = eliminarDatos[indice];
                System.out.println("" + elim);
                listaPeronasClienteActual.remove(elim);                
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona uno o mas datos de la tabla" , "Mensaje", JOptionPane.WARNING_MESSAGE);
        }
        clienteActualTablaPersonas.setListaPersonas(listaPeronasClienteActual);
        listado.set(indiceClienteActual, clienteActualTablaPersonas);
        actualizarTablaPersona(clienteActualTablaPersonas);
        PersistenciaCliente.SaveData(listado);
    }//GEN-LAST:event_btnEliminarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }
    
    public void  LimpiarTablaCliente(){
        DefaultTableModel df = ((DefaultTableModel) TablaCliente.getModel());
        int a = df.getRowCount() -1;
        for (int i = a; i >= 0; i--) {
            df.removeRow(i);
        }
    }
    
    public void LlenarTablaCliente(){
        LimpiarTablaCliente();
        ArrayList<Cliente> lista = PersistenciaCliente.LoadData();
        DefaultTableModel df = ((DefaultTableModel) TablaCliente.getModel());
        for (Cliente a : lista) {
            df.addRow(new Object[]{a.getNombre(), a.getApellido(), a.getDireccion(), a.getTelefono(), a.getId()});
        }
    }
        
    private void rellenarTablaCliente(){
        LimpiarTablaCliente();
        LlenarTablaCliente();
    }
    
    private void actualizarIDCliente(){
        listado =  PersistenciaCliente.LoadData();
        if(listado.size() > 0){
            contID = listado.size() - 1;
            //System.out.println("" + contID);
            ultimo = listado.get(contID);
            contID = ultimo.getId() + 1;
        }
        else{contID = 1;}
        
        txtIDCliente.setText("" + contID);
    }
    
    private void llenarCbCliente(javax.swing.JComboBox cbCli){
        listado =  PersistenciaCliente.LoadData();
        try{    
            for(Cliente x: listado){
                String m = (x.getId() + ": " + x.getNombre() + " " + x .getApellido());
                cbCli.addItem(m);
                
            }
        }catch(NullPointerException et){}
    }
    private void actualizarCbCliente(javax.swing.JComboBox cbCli){
        cbCli.removeAllItems();
        cbCli.addItem("Seleccione");
        llenarCbCliente(cbCli);
    }
    
    public void  LimpiarTablaPersona(){
        DefaultTableModel df = ((DefaultTableModel) TablaPersona.getModel());
        int a = df.getRowCount() -1;
        for (int i = a; i >= 0; i--) {
            df.removeRow(i);
        }
    }
    
    public void LlenarTablaPersona(Cliente cli){
        listaPeronasClienteActual = cli.getListaPersonas();
        DefaultTableModel df = ((DefaultTableModel) TablaPersona.getModel());
        for (Persona a : listaPeronasClienteActual) {
           df.addRow(new Object[]{
               a.getNombre(),
               a.getApellidos(),
               a.getDireccion(),
               a.getTelefono(),
               cli.getId(),
               cli.getNombre()
           });
        }
    }
    
    private void actualizarTablaPersona(Cliente cli){
        LimpiarTablaPersona();
        LlenarTablaPersona(cli);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCliente;
    private javax.swing.JTable TablaPersona;
    private javax.swing.JButton btnBorrarCamposClientes;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarPersona;
    private javax.swing.JButton btnInsertarCliente;
    private javax.swing.JButton btnInsertarPersona;
    private javax.swing.JComboBox cbClientesPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblErrorTelefono;
    private javax.swing.JLabel lblMensajePersona;
    private javax.swing.JLabel lblMensajeTelefonoPersona;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoCliente;
    private javax.swing.JTextField txtApellidoPersona;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtDireccionPersona;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTelefonoPersona;
    // End of variables declaration//GEN-END:variables
}
